language: generic
os: linux
dist: trusty

matrix:
  include:
    - language: android
      jdk: openjdk8
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.3
          - extra-android-support
          - extra-android-m2repository
          - android-19
          - sys-img-armeabi-v7a-android-19
          # Unfortunately travis uses the old android sdk tool instead of the new sdkmanager.
          # In this deprecated android sdk tool there is no ndk-bundle or cmake package!
        licenses:
          - '.+'
      before_install:
        # Install NDK and cmake via android sdkmanager. Unfortunately to acknowledge the licenses
        # takes a while. Looks like the "echo y" solution is not working. Needs improvement!
        - export TERM=dumb
        - touch ~/.android/repositories.cfg
        - mkdir -p /usr/local/android-sdk/licenses
        - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > /usr/local/android-sdk/licenses/android-sdk-license
        - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> /usr/local/android-sdk/licenses/android-sdk-license
        # Install NDK and cmake via android sdkmanager.
        - /usr/local/android-sdk/tools/bin/sdkmanager --update > /dev/null
        - echo "y" | /usr/local/android-sdk/tools/bin/sdkmanager "emulator" "ndk-bundle" "cmake;3.6.4111459" > /dev/null
      before_script:
        - export TERM=dumb
        - export _NO_CHECK_SIGNATURE=true
        - echo no | /usr/local/android-sdk/tools/bin/avdmanager create avd -n test -k "system-images;android-19;default;armeabi-v7a"
        - /usr/local/android-sdk/emulator/emulator -avd test -no-audio -no-window -dns-server 8.8.8.8 &
        - android-wait-for-emulator || android-wait-for-emulator
        - /usr/local/android-sdk/platform-tools/adb shell input keyevent 82 &
      script:
        # Using the ninja build command. Is much faster then make build command.
        - /usr/local/android-sdk/cmake/3.6.4111459/bin/cmake -G'Android Gradle - Ninja' -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/usr/local/android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-19 -DCMAKE_MAKE_PROGRAM=/usr/local/android-sdk/cmake/3.6.4111459/bin/ninja -DPEGTL_BUILD_EXAMPLES=OFF
        - /usr/local/android-sdk/cmake/3.6.4111459/bin/cmake --build . --target all
        - /usr/local/android-sdk/cmake/3.6.4111459/bin/ctest --output-on-failure


    - language: android
      jdk: openjdk8
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.3
          - extra-android-support
          - extra-android-m2repository
          - android-22
          - sys-img-armeabi-v7a-android-22
          # Unfortunately travis uses the old android sdk tool instead of the new sdkmanager.
          # In this deprecated android sdk tool there is no ndk-bundle or cmake package!
        licenses:
          - '.+'
      before_install:
        # Install NDK and cmake via android sdkmanager. Unfortunately to acknowledge the licenses
        # takes a while. Looks like the "echo y" solution is not working. Needs improvement!
        - export TERM=dumb
        - touch ~/.android/repositories.cfg
        - mkdir -p /usr/local/android-sdk/licenses
        - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > /usr/local/android-sdk/licenses/android-sdk-license
        - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> /usr/local/android-sdk/licenses/android-sdk-license
        # Install NDK and cmake via android sdkmanager.
        - /usr/local/android-sdk/tools/bin/sdkmanager --update > /dev/null
        - echo "y" | /usr/local/android-sdk/tools/bin/sdkmanager "emulator" "ndk-bundle" "cmake;3.6.4111459" > /dev/null
      before_script:
        - export TERM=dumb
        - export _NO_CHECK_SIGNATURE=true
        - echo no | /usr/local/android-sdk/tools/bin/avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
        - /usr/local/android-sdk/emulator/emulator -avd test -no-audio -no-window -dns-server 8.8.8.8 &
        - android-wait-for-emulator || android-wait-for-emulator
        - /usr/local/android-sdk/platform-tools/adb shell input keyevent 82 &
      script:
        # Using the ninja build command. Is much faster then make build command.
        - /usr/local/android-sdk/cmake/3.6.4111459/bin/cmake -G'Android Gradle - Ninja' -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/usr/local/android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-22 -DCMAKE_MAKE_PROGRAM=/usr/local/android-sdk/cmake/3.6.4111459/bin/ninja -DPEGTL_BUILD_EXAMPLES=OFF
        - /usr/local/android-sdk/cmake/3.6.4111459/bin/cmake --build . --target all
        - /usr/local/android-sdk/cmake/3.6.4111459/bin/ctest --output-on-failure

script:
  - $CXX --version
  - make -kj3
